=== yohahn/java-xsd-jaxb/src/main/resources/testCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:target="http://www.yohahnandcompany.com/testCase"
           targetNamespace="http://www.yohahnandcompany.com/testCase"
           elementFormDefault="qualified">

    <xs:element name="testCase" type="target:testCase"/>

    <xs:complexType name="testCase">
        <xs:sequence>
            <xs:element name="testStep" type="target:testStep" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="testStep">
        <xs:sequence>
            <xs:element name="inputMessage" type="target:inputMessage" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="inputMessage">
        <xs:sequence>
            <xs:element name="headerFile" type="xs:string"/>
            <xs:element name="payloadFile" type="xs:string"/>
            <xs:element name="expectedOutput" type="target:expectedOutput"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="expectedOutput" abstract="true">
        <xs:sequence/>
    </xs:complexType>

    <xs:complexType name="expectedMessage">
        <xs:complexContent>
            <xs:extension base="target:expectedOutput">
                <xs:sequence>
                    <xs:element name="message" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="expectedDBChange">
        <xs:complexContent>
            <xs:extension base="target:expectedOutput">
                <xs:sequence>
                    <xs:element name="dbChange" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== yohahn/java-xsd-jaxb/src/main/resources/testCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<testCase xmlns="http://www.yohahnandcompany.com/testCase"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.yohahnandcompany.com/testCase testCase.xsd"
          name="test case 1">
    <testStep name="test step 1">
        <inputMessage>
            <headerFile>some/loc/header_1_1</headerFile>
            <payloadFile>some/loc/payload_1_1</payloadFile>
            <expectedOutput xsi:type="expectedMessage">
                <message>ACK</message>
            </expectedOutput>
        </inputMessage>
        <inputMessage>
            <headerFile>some/loc/header_1_2</headerFile>
            <payloadFile>some/loc/payload_1_2</payloadFile>
            <expectedOutput xsi:type="expectedDBChange">
                <dbChange>TBL_LOAN.APPROVED=TRUE</dbChange>
            </expectedOutput>
        </inputMessage>
    </testStep>
    <testStep name="test step 2">
        <inputMessage>
            <headerFile>some/loc/header_2_1</headerFile>
            <payloadFile>some/loc/payload_2_1</payloadFile>
            <expectedOutput xsi:type="expectedMessage">
                <message>ERR</message>
            </expectedOutput>
        </inputMessage>
    </testStep>
</testCase>
